runtime: java11
env: standard
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
handlers:
  - url: /.*
    script: this field is required, but ignored
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}